version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: jobtracker
      POSTGRES_USER: jt_user
      POSTGRES_PASSWORD: change_me
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '8081:80'
    depends_on:
      - postgres

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_USERNAME: jt_user
      KC_DB_PASSWORD: change_me
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    ports:
      - '8080:8080'
    depends_on:
      - postgres

  zookeeper:
    image: bitnami/zookeeper:3
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'
    ports:
      - '2181:2181'

  kafka:
    image: bitnami/kafka:3
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
      ALLOW_PLAINTEXT_LISTENER: 'yes'
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
      - postgres

  backend:
    build: ./backend
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/jobtracker
      SPRING_DATASOURCE_USERNAME: jt_user
      SPRING_DATASOURCE_PASSWORD: change_me
      KEYCLOAK_ISSUER_URI: http://keycloak:8080/realms/jobtracker
    ports:
      - '8082:8082'
    depends_on:
      - postgres
      - kafka
      - keycloak

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      VITE_API_BASE: http://backend:8082/api
    ports:
      - '5173:5173'
    depends_on:
      - backend

volumes:
  pgdata:
