server:
  port: 9395
  max-http-request-header-size: 32KB

spring:
  application:
    name: job-app-tracker

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

  datasource:
    url: jdbc:postgresql://localhost:5432/job-app-tracker
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # drop & recreate tables (use 'update' for dev, not prod)
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  web:
    cors:
      allowed-origins: "http://localhost:5173"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allow-credentials: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      livenessState:
        enabled: true
      readinessState:
        enabled: true

# Optional info section
#info:
#  app:
#    name: job-app-tracker
#    description: Job Application Tracker with Docker Compose
#    version: 0.0.1-SNAPSHOT
